import React from 'react';
import ExecutiveSummaryCard from './ExecutiveSummaryCard';
import FinancialReconciliationTable from './FinancialReconciliationTable';
import LegalRiskGrid from './LegalRiskGrid';
import NegotiationPlaybook from './NegotiationPlaybook';
import { RefreshCw, LayoutDashboard } from 'lucide-react';

export default function Dashboard({ pipelineResult, onReset }) {
  if (!pipelineResult) return null;

  return (
    <div className="min-h-screen bg-[#0a0c10] text-slate-200">
      <nav className="sticky top-0 z-50 bg-[#0a0c10]/80 backdrop-blur-xl border-b border-slate-800 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2 px-3 py-1 bg-indigo-500/10 border border-indigo-500/20 rounded-lg">
            <LayoutDashboard className="w-4 h-4 text-indigo-400" />
            <span className="text-sm font-bold text-indigo-400 uppercase tracking-tighter">Report</span>
          </div>
          <h1 className="text-lg font-bold text-white tracking-tight">
            Diligence<span className="text-indigo-500">.dev</span>
            <span className="mx-3 text-slate-700 font-light">/</span>
            <span className="text-slate-300">{pipelineResult.deal.businessName}</span>
          </h1>
        </div>
        <button
          onClick={onReset}
          className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white text-sm font-bold rounded-xl transition-all"
        >
          <RefreshCw className="w-4 h-4" />
          New Analysis
        </button>
      </nav>

      <main className="max-w-7xl mx-auto px-6 py-12 space-y-12">
        <ExecutiveSummaryCard deal={pipelineResult.deal} agentFour={pipelineResult.agentFour} />
        <FinancialReconciliationTable agentTwo={pipelineResult.agentTwo} />
        <LegalRiskGrid agentThree={pipelineResult.agentThree} />
        <NegotiationPlaybook agentFour={pipelineResult.agentFour} />
      </main>

      <footer className="border-t border-slate-900 py-12 text-center text-slate-600 text-xs">
        Generated by Diligence.dev Autonomous Agent Pipeline • {new Date(pipelineResult.deal.analysisTimestamp).toLocaleString()}
      </footer>
    </div>
  );
}
